config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  devise_for :users, controllers: { registrations: :registrations }

  devise_scope :user do
    get '/account', to: 'registrations#show', as: 'account'
  end

  resources :instructors
  resources :programs, param: :name do
    resources :lessons, param: :number do
      resources :surveys
    end
    resources :memberships, only: [:create, :destroy]
    member do
      get 'manage'
    end
  end

  root to: 'programs#index'

end

app/models/program.rb
class Program < ApplicationRecord
  has_many :memberships
  has_many :users, through: :memberships
  has_many :lessons

  validates :name, presence: true
  validates :location, presence: true
  validates_uniqueness_of :name
end

app/controllers/programs_controller.rb
class ProgramsController < ApplicationController
  before_action :authenticate_user!

  def index
    if current_user.producer?
      @active_programs = Program.where(active: true).order(:created_at)
      @inactive_programs = Program.where(active: false).order(:created_at)
    else
      @active_programs = current_user.programs.where(active: true).order(:created_at)
      @inactive_programs = current_user.programs.where(active: false).order(:created_at)
    end
    respond_to do |format|
      format.html
      format.csv {
        send_data Program.export_collection_to_csv,
          :type => 'text/csv; charset=UTF-8;',
          :disposition => "attachment; filename=All_Programs_#{Date.current}.csv"
      }
    end
  end

  def show
    @program = Program.find_by(name: params[:name])
    @instructors = @program.users
    @lessons = @program.lessons.order(:date)

    if !current_user.producer? && !current_user.programs.include?(@program)
      flash[:alert] = "You do not have access to this program"
      redirect_to programs_path
    end
  end

  def new
    @program = Program.new
  end

  def create
    @program = Program.new(program_params)
    if @program.save
      redirect_to program_path(@program.name)
    else
      render :new
    end
  end

  def edit
    @program = Program.find_by(name: params[:name])
  end

  def update
    @program = Program.find_by(name: params[:name])
    if @program.update(program_params)
      redirect_to program_path(@program.name)
    else
      render :edit
    end
  end

  def destroy
    @program = Program.find_by(name: params[:name])
    if @program.destroy
      redirect_to programs_path
    else
      render :edit
    end
  end

  def manage
    @program = Program.find_by(name: params[:name])
    @membership = @program.memberships.new
    @instructors = @program.users
    @users = User.all.select do |user|
      !@instructors.include?(user)
    end
  end

  private

  def program_params
    params.require(:program).permit(:name, :location, :active)
  end
end

app/views/programs/_lesson_row.html.erb
<%= link_to program_lesson_path(@program.name, lesson.number), class: "lesson-row" do %>
<div><%= lesson.number %></div>
<div><%= lesson.date.strftime("%a, %b %d, %Y ") %></div>
<div><%= lesson.name %></div>
<div <%= color_of(lesson.avg_rating) %>><%= lesson.avg_rating || 'N/A' %></div>
<div><%= lesson.instructor.name %></div>
<% end %>

app/views/programs/edit.html.erb
<main>
  <% if @program.errors.full_messages.any? %>
    <div>
      <% @program.errors.full_messages.each do |error_message| %>
        <p><%= error_message %></p>
      <% end %>
    </div>
  <% end %>
  <%= form_for @program, url: program_path(@program.name) do |f| %>
    <%= f.label :name, "Program Name" %>
    <%= f.text_field :name %>

    <%= f.label :location, "Program Location" %>
    <%= f.text_field :location %>

    <%= f.label :active, "Status" %>
    <%= f.select :active, options_for_select([["Active", true], ["Inactive", false]], @program.active?) %>

    <%= f.submit "Update Program" %>
  <% end %>
  <%= form_for @program, url: program_path(@program.name), method: :delete, data: { confirm: "Are you sure?" } do |f| %>
    <%= f.submit "Delete Program" %>
  <% end %>
</main>

app/views/programs/index.html.erb
<main>
  <div>
    <h2>Options</h2>
    <% if current_user.producer? %>
      <%= link_to "New Program", new_program_path, class: "button" %>
      <%= link_to "Export Program Data", programs_path(format: "csv"), class: "button" %>
    <% end %>
  </div>
  <div>
    <h2>Active Programs</h2>
    <% @active_programs.each do |program| %>
      <%= link_to program.name, program_path(program.name), class: "button" %>
    <% end %>
  </div>
  <div>
    <h2>Inactive Programs</h2>
    <% @inactive_programs.each do |program| %>
      <%= link_to program.name, program_path(program.name), class: "button" %>
    <% end %>
  </div>
</main>

app/views/programs/manage.html.erb
<main>
  <% if @membership.errors.full_messages.any? %>
    <div>
      <% @membership.errors.full_messages.each do |error_message| %>
        <p><%= error_message %></p>
      <% end %>
    </div>
  <% end %>
  <h3>Current Instructors: </h3>
  <% @instructors.each do |instructor| %>
      <p>
        <%= instructor.name %>
        <%= link_to "Remove", program_membership_path(@program.name, instructor), method: :delete %>
      </p>
  <% end %>
  <h3>Add New Instructors:</h3>
  <%= form_for @membership, url: program_memberships_path(@program.name) do |f| %>
    <%= f.collection_select :user_id, @users, :id, :name %>
    <%= f.submit "Add Instructor"%>
  <% end %>
</main>

app/views/programs/new.html.erb
<main>
  <% if @program.errors.full_messages.any? %>
    <div>
      <% @program.errors.full_messages.each do |error_message| %>
        <p><%= error_message %></p>
      <% end %>
    </div>
  <% end %>
  <%= form_for @program do |f| %>
    <%= f.label :name, "Program Name" %>
    <%= f.text_field :name %>

    <%= f.label :location, "Program Location" %>
    <%= f.text_field :location %>

    <%= f.submit "Create Program" %>
  <% end %>
</main>

app/views/programs/show.html.erb
<main class="program-show">
  <section class="program-info">
    <h3>Location:</h3>
    <p><%= @program.location %></p>
    <h3>Status:</h3>
    <% if @program.active? %>
      <p class="green"><strong>Active</strong></p>
    <% else %>
      <p class="red"><strong>Inactive</strong></p>
    <% end %>
    <% if current_user.producer? %>
      <p>
        <%= link_to "Edit Program", edit_program_path(@program.name), class: "button" %>
      </p>
    <% end %>
    <h3>Instructors:</h3>
    <% @instructors.each do |instructor| %>
    <p><%= instructor.name %></p>
    <% end %>
    <% if current_user.producer? %>
      <p>
        <%= link_to "Manage Instructors", manage_program_path(@program.name), class: "button" %>
      </p>
    <% end %>
  </section>
  <section class="lesson-gallery">
    <div>
      <h3>Lessons</h3>
      <%= link_to "New Lesson", new_program_lesson_path(@program.name), class: "button" %>
      <%= link_to "Export Lesson Data", program_lessons_path(@program.name, format: "csv"), class: "button" %>
    </div>
    <div class="lesson-table">
      <div class="lesson-header">
        <div>Number</div>
        <div>Date</div>
        <div>Lesson</div>
        <div>Average Rating</div>
        <div>Instructor</div>
      </div>
      <% @lessons.each do |lesson| %>
        <%= render partial: "lesson_row", locals: {lesson: lesson} %>
      <% end %>
    </div>
  </section>
</main>