config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  devise_for :users, controllers: { registrations: :registrations }

  devise_scope :user do
    get '/account', to: 'registrations#show', as: 'account'
  end

  resources :instructors
  resources :programs, param: :name do
    resources :lessons, param: :number do
      resources :surveys
    end
    resources :memberships, only: [:create, :destroy]
    member do
      get 'manage'
    end
  end

  root to: 'programs#index'

end

app/models/lesson.rb
class Lesson < ApplicationRecord
  belongs_to :program
  belongs_to :user
  alias_attribute :instructor, :user

  has_many :surveys

  validates :number, :name, :date, :start_time, :end_time, :user_id, presence: true
  validates_uniqueness_of :number, scope: :program_id
end

app/controllers/lessons_controller.rb
class LessonsController < ApplicationController
  before_action :authenticate_user!

  def index
    @program = Program.find_by(name: params[:program_name])

    respond_to do |format|
      format.csv {
        send_data Lesson.export_collection_to_csv(program: @program),
        :type => 'text/csv; charset=UTF-8;',
        :disposition => "attachment; filename=#{@program.name}_Lessons_#{Date.current}.csv"
      }
    end
  end

  def show
    @program = Program.find_by(name: params[:program_name])
    @lesson = @program.lessons.find_by(number: params[:number])
    @surveys = @lesson.surveys.order(:created_at)
    @instructor = @lesson.instructor

    if @surveys.length > 0
      sum_lo = @surveys.reduce(0) do |acc, survey|
        acc + survey.lo_rating
      end
      @avg_lo_rating = (sum_lo.to_f / @surveys.length).round(1)

      sum_delivery = @surveys.reduce(0) do |acc, survey|
        acc + survey.delivery_rating
      end
      @avg_delivery_rating = (sum_delivery.to_f / @surveys.length).round(1)

      sum_comfort = @surveys.reduce(0) do |acc, survey|
        acc + survey.comfort_rating
      end
      @avg_comfort_rating = (sum_comfort.to_f / @surveys.length).round(1)
    else
      @avg_lo_rating = 0
      @avg_delivery_rating = 0
      @avg_comfort_rating = 0
    end

  end

  def new
    @program = Program.find_by(name: params[:program_name])
    @lesson = @program.lessons.new
    @suggested_lesson_number = @program.lessons.length
    @instructors = @program.users
  end

  def create
    @program = Program.find_by(name: params[:program_name])
    @lesson = @program.lessons.new(lesson_params)
    @instructors = @program.users
    if @lesson.save
      redirect_to program_lesson_path(@program.name, @lesson.number)
    else
      render :new
    end
  end

  def edit
    @program = Program.find_by(name: params[:program_name])
    @lesson = @program.lessons.find_by(number: params[:number])
    @instructors = @program.users
  end

  def update
    @program = Program.find_by(name: params[:program_name])
    @lesson = @program.lessons.find_by(number: params[:number])
    @instructors = @program.users
    if @lesson.update(lesson_params)
      redirect_to program_lesson_path(@program.name, @lesson.number)
    else
      render :edit
    end
  end

  def destroy
    @program = Program.find_by(name: params[:program_name])
    @lesson = @program.lessons.find_by(number: params[:number])
    if @lesson.destroy
      redirect_to program_path(@program.name)
    else
      render :edit
    end
  end

  private

  def lesson_params
    params.require(:lesson).permit(:number, :name, :date, :start_time, :end_time, :user_id)
  end
end

app/views/lessons/_survey_comments_row.html.erb
<%= link_to program_lesson_survey_path(@program.name, @lesson.number, survey, student: survey.respondent_name), class: "survey-row" do %>
  <div><%= survey.respondent_name %></div>
  <div><%= survey.positive_comment %></div>
  <div><%= survey.negative_comment %></div>
  <div><%= survey.general_comment %></div>
  <div>
    <% if survey.attended_office_hours? %>
      &check;
    <% end %>
  </div>
<% end %>

app/views/lessons/_survey_ratings_row.html.erb
<%= link_to program_lesson_survey_path(@program.name, @lesson.number, survey, student: survey.respondent_name), class: "survey-row" do %>
  <div><%= survey.respondent_name %></div>
  <div <%= color_of(survey.lo_rating) %>><%= survey.lo_rating %></div>
  <div <%= color_of(survey.delivery_rating) %>><%= survey.delivery_rating %></div>
  <div <%= color_of(survey.comfort_rating) %>><%= survey.comfort_rating %></div>
  <div>
    <% if survey.attended_office_hours? %>
      &check;
    <% end %>
  </div>
<% end %>

app/views/lessons/_survey_row.html.erb
<%= link_to program_lesson_survey_path(@program, @lesson, survey), class: "survey-row" do %>
  <div><%= survey.respondent_name %></div>
  <div <%= color_of(survey.lo_rating) %>><%= survey.lo_rating %></div>
  <div <%= color_of(survey.delivery_rating) %>><%= survey.delivery_rating %></div>
  <div <%= color_of(survey.comfort_rating) %>><%= survey.comfort_rating %></div>
  <div>
    <% if survey.attended_office_hours? %>
      &check;
    <% end %>
  </div>
<% end %>

app/views/lessons/edit.html.erb
<main>
  <% if @lesson.errors.full_messages.any? %>
    <div>
      <% @lesson.errors.full_messages.each do |error_message| %>
        <p><%= error_message %></p>
      <% end %>
    </div>
  <% end %>
  <%= form_for @lesson, url: program_lesson_path(@program.name, @lesson.number) do |f| %>
    <%= f.label :number, "Lesson Number" %>
    <%= f.number_field :number %>

    <%= f.label :name, "Lesson Name" %>
    <%= f.text_field :name %>

    <%= f.label :date, "Lesson Date" %>
    <%= f.date_field :date %>

    <%= f.label :start_time, "Lesson Start Time" %>
    <%= f.time_field :start_time %>

    <%= f.label :end_time, "Lesson End Time" %>
    <%= f.time_field :end_time %>

    <%= f.label :user_id, "Instructor" %>
    <%= f.collection_select :user_id, @instructors, :id, :name %>
    <br />
    <%= f.submit "Update Lesson" %>
  <% end %>
  <%= form_for @lesson, url: program_lesson_path(@program.name, @lesson.number), method: :delete, data: { confirm: 'Are you sure?' } do |f| %>
    <%= f.submit "Delete Lesson" %>
  <% end %>
</main>

app/views/lessons/new.html.erb
<main>
  <% if @lesson.errors.full_messages.any? %>
    <div>
      <% @lesson.errors.full_messages.each do |error_message| %>
        <p><%= error_message %></p>
      <% end %>
    </div>
  <% end %>
  <%= form_for @lesson, url: program_lessons_path(@program.name) do |f| %>
    <%= f.label :number, "Lesson Number" %>
    <%= f.number_field :number, value: @suggested_lesson_number %>

    <%= f.label :name, "Lesson Name" %>
    <%= f.text_field :name %>

    <%= f.label :date, "Lesson Date" %>
    <%= f.date_field :date %>

    <%= f.label :start_time, "Lesson Start Time" %>
    <%= f.time_field :start_time %>

    <%= f.label :end_time, "Lesson End Time" %>
    <%= f.time_field :end_time %>

    <%= f.label :user_id, "Instructor" %>
    <%= f.collection_select :user_id, @instructors, :id, :name %>
    <br />
    <%= f.submit "Add Lesson" %>
  <% end %>
</main>

app/views/lessons/show.html.erb
<main class="lesson-show">
  <section class="lesson-info">
    <p><%= @lesson.date.strftime("%A, %B %d, %Y ") %></p>
    <p><%= @lesson.start_time.strftime("%I:%M%p") %> - <%= @lesson.end_time.strftime("%I:%M%p") %></p>
    <p>Instructor: <%= @instructor.name %></p>
    <p>
      <%= link_to "Edit Lesson", edit_program_lesson_path(@program.name, @lesson.number), class: "button" %>
    </p>
    <div class="average-header">Learning Objectives Rating</div>
    <div class="average-row" <%= color_of(@avg_lo_rating) %>><%= @avg_lo_rating %></div>
    <div class="average-header">Delivery Rating</div>
    <div class="average-row" <%= color_of(@avg_delivery_rating) %>><%= @avg_delivery_rating %></div>
    <div class="average-header">Comfort Rating</div>
    <div class="average-row" <%= color_of(@avg_comfort_rating) %>><%= @avg_comfort_rating %></div>
  </section>
  <section class="survey-gallery">
    <div class="flex-header">
      <h3>Survey Responses</h3>
    </div>
    <% if params[:view] != "comments" %>
      <%= link_to "New Survey", new_program_lesson_survey_path(@program.name, @lesson.number), class: "button" %>
      <%= link_to "Export Survey Data", program_lesson_surveys_path(@program.name, @lesson.number, format: "csv"), class: "button" %>
      <%= link_to "Toggle Comments List", program_lesson_path(@program.name, @lesson.number, view: "comments"), class: "button" %>
      <div class="survey-table">
        <div class="survey-header">
          <div>Respondent</div>
          <div>Learning Objectives</div>
          <div>Delivery</div>
          <div>Comfort</div>
          <div>Office Hours Attended</div>
        </div>
        <% @surveys.each do |survey| %>
          <%= render partial: "survey_ratings_row", locals: {survey: survey}%>
        <% end %>
      </div>
    <% else %>
      <%= link_to "New Survey", new_program_lesson_survey_path(@program.name, @lesson.number), class: "button" %>
      <%= link_to "Export Survey Data", program_lesson_surveys_path(@program.name, @lesson.number, format: "csv"), class: "button" %>
      <%= link_to "Toggle Ratings List", program_lesson_path(@program.name, @lesson.number), class: "button" %>
      <div class="survey-table">
        <div class="survey-header">
          <div>Respondent</div>
          <div>Positive Comments</div>
          <div>Negative Comments</div>
          <div>General Comments</div>
          <div>Office Hours Attended</div>
        </div>
        <% @surveys.each do |survey| %>
          <%= render partial: "survey_comments_row", locals: {survey: survey}%>
        <% end %>
      </div>
    <% end %>


  </section>
</main>