config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  devise_for :users, controllers: { registrations: :registrations }

  devise_scope :user do
    get '/account', to: 'registrations#show', as: 'account'
  end

  resources :instructors
  resources :programs, param: :name do
    resources :lessons, param: :number do
      resources :surveys
    end
    resources :memberships, only: [:create, :destroy]
    member do
      get 'manage'
    end
  end

  root to: 'programs#index'

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ExitTicketApp</title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= favicon_link_tag 'favicon.png' %>
  </head>
  <body>
    <nav class="site-wide">
      <% if signed_in? %>
        <h1><%= link_to root_path do %><span class="logo">GA </span>Exit Tickets<% end %></h1>
      <% else %>
        <h1 class="banner-logo"><span class="logo">GA </span>Exit Tickets</h1>
      <% end %>
      <span class="separate"></span>
      <% if current_user %>
        <%= link_to current_user.email, account_path %>
        <%= link_to "Sign Out", destroy_user_session_path, method: :delete %>
      <% end %>
    </nav>
    <nav class="breadcrumbs">
      <% if signed_in? %>
        <% if @program && @program.id %>
          <%= link_to @program.name, program_path(@program.name) %>
        <% end %>
        <% if @lesson && @lesson.id %>
          <%= link_to "Lesson: #{@lesson.name}", program_lesson_path(@program.name, @lesson.number) %>
        <% end %>
        <% if @survey && @survey.id %>
          <%= link_to "Survey: #{@survey.respondent_name}", program_lesson_survey_path(@program.name, @lesson.number, @survey, student: @survey.respondent_name) %>
        <% end %>
      <% else %>
        <% if @program && @program.id %>
          <span><%= @program.name %></span>
        <% end %>
        <% if @lesson && @lesson.id %>
          <span><%= "Lesson: #{@lesson.name}" %></span>
        <% end %>
        <% if @survey && @survey.id %>
          <span><%= "Survey: #{@survey.respondent_name}" %></span>
        <% end %>
      <%end%>
    </nav>
    <%= yield %>
  </body>
</html>